linters:
  enable:
    - errcheck
    - misspell
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  disable:
    - govet

issues:
  exclude-rules:
    - path: tools/
      linters:
        - staticcheck
      text: "SA1019: .* is deprecated"
    - path: rpc/rpcApi/
      linters:
        - staticcheck
      text: "SA1019: .* is deprecated"