linters:
  enable:
    - errcheck
    - misspell
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - whitespace
  disable:
    - govet
linters-settings:
 staticcheck:
    checks:
      - all
      - '-SA1019' # allow the use of deprecated functions (since we have some)
