before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/keel
    ldflags:
      - -s -w -X 'github.com/teamkeel/keel/runtime.Version={{.Version}}' -X 'github.com/teamkeel/keel/cmd.enabledDebugFlags=false'
archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
release:
  github:
    owner: teamkeel
    name: cli
  prerelease: auto
brews:
  - name: "{{ .Env.HOMEBREW_ALIAS }}"
    url_template: "https://github.com/teamkeel/cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://github.com/teamkeel/cli"
    install: |
      bin.install "cli" => "{{ .Env.HOMEBREW_ALIAS }}"
    # Repository to push the generated files to.
    repository:
      owner: teamkeel
      name: "{{ .Env.HOMEBREW_REPO }}"
      branch: "main"
      pull_request:
        enabled: true
        draft: true
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
