before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/keel
    ldflags:
      - -s -w -X 'github.com/teamkeel/keel/runtime.Version={{.Version}}' -X 'github.com/teamkeel/keel/cmd.enabledDebugFlags=false'
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
release:
  github:
    owner: teamkeel
    name: keel
brews:
  - name: keel
    url_template: "https://github.com/teamkeel/keel/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://github.com/teamkeel/keel"
    install: |
      bin.install "keel"
    tap:
      owner: teamkeel
      name: homebrew-keel
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
