const PROTO_ACTION_TYPES = {
  UNKNOWN: "OPERATION_TYPE_UNKNOWN",
  CREATE: "OPERATION_TYPE_CREATE",
  GET: "OPERATION_TYPE_GET",
  LIST: "OPERATION_TYPE_LIST",
  UPDATE: "OPERATION_TYPE_UPDATE",
  DELETE: "OPERATION_TYPE_DELETE",
  READ: "OPERATION_TYPE_READ",
  WRITE: "OPERATION_TYPE_WRITE",
  JOB: "JOB_TYPE",
  SUBSCRIBER: "SUBSCRIBER_TYPE",
};

module.exports.PROTO_ACTION_TYPES = PROTO_ACTION_TYPES;
