const PROTO_ACTION_TYPES = {
  UNKNOWN: "ACTION_TYPE_UNKNOWN",
  CREATE: "ACTION_TYPE_CREATE",
  GET: "ACTION_TYPE_GET",
  LIST: "ACTION_TYPE_LIST",
  UPDATE: "ACTION_TYPE_UPDATE",
  DELETE: "ACTION_TYPE_DELETE",
  READ: "ACTION_TYPE_READ",
  WRITE: "ACTION_TYPE_WRITE",
  JOB: "JOB_TYPE",
  SUBSCRIBER: "SUBSCRIBER_TYPE",
  FLOW: "FLOW_TYPE",
};

export { PROTO_ACTION_TYPES };
