// Code generated by protoc-gen-twirp v8.1.3, DO NOT EDIT.
// source: rpc.proto

package rpc

import context "context"
import fmt "fmt"
import http "net/http"
import io "io"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto1 "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

import bytes "bytes"
import errors "errors"
import path "path"
import url "net/url"

// Version compatibility assertion.
// If the constant is not defined in the package, that likely means
// the package needs to be updated to work with this generated code.
// See https://twitchtv.github.io/twirp/docs/version_matrix.html
const _ = twirp.TwirpPackageMinVersion_8_1_0

// =============
// API Interface
// =============

type API interface {
	GetActiveSchema(context.Context, *GetSchemaRequest) (*GetSchemaResponse, error)

	RunSQLQuery(context.Context, *SQLQueryInput) (*SQLQueryResponse, error)

	GetTrace(context.Context, *GetTraceRequest) (*GetTraceResponse, error)

	ListTraces(context.Context, *ListTracesRequest) (*ListTracesResponse, error)

	// Return a list of default generated tools config for interacting with the API
	ListTools(context.Context, *ListToolsRequest) (*ListToolsResponse, error)
}

// ===================
// API Protobuf Client
// ===================

type aPIProtobufClient struct {
	client      HTTPClient
	urls        [5]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewAPIProtobufClient creates a Protobuf client that implements the API interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewAPIProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) API {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "rpc", "API")
	urls := [5]string{
		serviceURL + "GetActiveSchema",
		serviceURL + "RunSQLQuery",
		serviceURL + "GetTrace",
		serviceURL + "ListTraces",
		serviceURL + "ListTools",
	}

	return &aPIProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *aPIProtobufClient) GetActiveSchema(ctx context.Context, in *GetSchemaRequest) (*GetSchemaResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "rpc")
	ctx = ctxsetters.WithServiceName(ctx, "API")
	ctx = ctxsetters.WithMethodName(ctx, "GetActiveSchema")
	caller := c.callGetActiveSchema
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetSchemaRequest) (*GetSchemaResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetSchemaRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetSchemaRequest) when calling interceptor")
					}
					return c.callGetActiveSchema(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetSchemaResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetSchemaResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *aPIProtobufClient) callGetActiveSchema(ctx context.Context, in *GetSchemaRequest) (*GetSchemaResponse, error) {
	out := new(GetSchemaResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *aPIProtobufClient) RunSQLQuery(ctx context.Context, in *SQLQueryInput) (*SQLQueryResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "rpc")
	ctx = ctxsetters.WithServiceName(ctx, "API")
	ctx = ctxsetters.WithMethodName(ctx, "RunSQLQuery")
	caller := c.callRunSQLQuery
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *SQLQueryInput) (*SQLQueryResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SQLQueryInput)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SQLQueryInput) when calling interceptor")
					}
					return c.callRunSQLQuery(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SQLQueryResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SQLQueryResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *aPIProtobufClient) callRunSQLQuery(ctx context.Context, in *SQLQueryInput) (*SQLQueryResponse, error) {
	out := new(SQLQueryResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *aPIProtobufClient) GetTrace(ctx context.Context, in *GetTraceRequest) (*GetTraceResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "rpc")
	ctx = ctxsetters.WithServiceName(ctx, "API")
	ctx = ctxsetters.WithMethodName(ctx, "GetTrace")
	caller := c.callGetTrace
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetTraceRequest) (*GetTraceResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetTraceRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetTraceRequest) when calling interceptor")
					}
					return c.callGetTrace(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetTraceResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetTraceResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *aPIProtobufClient) callGetTrace(ctx context.Context, in *GetTraceRequest) (*GetTraceResponse, error) {
	out := new(GetTraceResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *aPIProtobufClient) ListTraces(ctx context.Context, in *ListTracesRequest) (*ListTracesResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "rpc")
	ctx = ctxsetters.WithServiceName(ctx, "API")
	ctx = ctxsetters.WithMethodName(ctx, "ListTraces")
	caller := c.callListTraces
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListTracesRequest) (*ListTracesResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListTracesRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListTracesRequest) when calling interceptor")
					}
					return c.callListTraces(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListTracesResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListTracesResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *aPIProtobufClient) callListTraces(ctx context.Context, in *ListTracesRequest) (*ListTracesResponse, error) {
	out := new(ListTracesResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *aPIProtobufClient) ListTools(ctx context.Context, in *ListToolsRequest) (*ListToolsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "rpc")
	ctx = ctxsetters.WithServiceName(ctx, "API")
	ctx = ctxsetters.WithMethodName(ctx, "ListTools")
	caller := c.callListTools
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListToolsRequest) (*ListToolsResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListToolsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListToolsRequest) when calling interceptor")
					}
					return c.callListTools(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListToolsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListToolsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *aPIProtobufClient) callListTools(ctx context.Context, in *ListToolsRequest) (*ListToolsResponse, error) {
	out := new(ListToolsResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[4], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ===============
// API JSON Client
// ===============

type aPIJSONClient struct {
	client      HTTPClient
	urls        [5]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewAPIJSONClient creates a JSON client that implements the API interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewAPIJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) API {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	literalURLs := false
	_ = clientOpts.ReadOpt("literalURLs", &literalURLs)
	var pathPrefix string
	if ok := clientOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(pathPrefix, "rpc", "API")
	urls := [5]string{
		serviceURL + "GetActiveSchema",
		serviceURL + "RunSQLQuery",
		serviceURL + "GetTrace",
		serviceURL + "ListTraces",
		serviceURL + "ListTools",
	}

	return &aPIJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *aPIJSONClient) GetActiveSchema(ctx context.Context, in *GetSchemaRequest) (*GetSchemaResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "rpc")
	ctx = ctxsetters.WithServiceName(ctx, "API")
	ctx = ctxsetters.WithMethodName(ctx, "GetActiveSchema")
	caller := c.callGetActiveSchema
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetSchemaRequest) (*GetSchemaResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetSchemaRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetSchemaRequest) when calling interceptor")
					}
					return c.callGetActiveSchema(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetSchemaResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetSchemaResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *aPIJSONClient) callGetActiveSchema(ctx context.Context, in *GetSchemaRequest) (*GetSchemaResponse, error) {
	out := new(GetSchemaResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *aPIJSONClient) RunSQLQuery(ctx context.Context, in *SQLQueryInput) (*SQLQueryResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "rpc")
	ctx = ctxsetters.WithServiceName(ctx, "API")
	ctx = ctxsetters.WithMethodName(ctx, "RunSQLQuery")
	caller := c.callRunSQLQuery
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *SQLQueryInput) (*SQLQueryResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SQLQueryInput)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SQLQueryInput) when calling interceptor")
					}
					return c.callRunSQLQuery(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SQLQueryResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SQLQueryResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *aPIJSONClient) callRunSQLQuery(ctx context.Context, in *SQLQueryInput) (*SQLQueryResponse, error) {
	out := new(SQLQueryResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *aPIJSONClient) GetTrace(ctx context.Context, in *GetTraceRequest) (*GetTraceResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "rpc")
	ctx = ctxsetters.WithServiceName(ctx, "API")
	ctx = ctxsetters.WithMethodName(ctx, "GetTrace")
	caller := c.callGetTrace
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *GetTraceRequest) (*GetTraceResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetTraceRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetTraceRequest) when calling interceptor")
					}
					return c.callGetTrace(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetTraceResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetTraceResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *aPIJSONClient) callGetTrace(ctx context.Context, in *GetTraceRequest) (*GetTraceResponse, error) {
	out := new(GetTraceResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *aPIJSONClient) ListTraces(ctx context.Context, in *ListTracesRequest) (*ListTracesResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "rpc")
	ctx = ctxsetters.WithServiceName(ctx, "API")
	ctx = ctxsetters.WithMethodName(ctx, "ListTraces")
	caller := c.callListTraces
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListTracesRequest) (*ListTracesResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListTracesRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListTracesRequest) when calling interceptor")
					}
					return c.callListTraces(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListTracesResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListTracesResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *aPIJSONClient) callListTraces(ctx context.Context, in *ListTracesRequest) (*ListTracesResponse, error) {
	out := new(ListTracesResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[3], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *aPIJSONClient) ListTools(ctx context.Context, in *ListToolsRequest) (*ListToolsResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "rpc")
	ctx = ctxsetters.WithServiceName(ctx, "API")
	ctx = ctxsetters.WithMethodName(ctx, "ListTools")
	caller := c.callListTools
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ListToolsRequest) (*ListToolsResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListToolsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListToolsRequest) when calling interceptor")
					}
					return c.callListTools(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListToolsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListToolsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *aPIJSONClient) callListTools(ctx context.Context, in *ListToolsRequest) (*ListToolsResponse, error) {
	out := new(ListToolsResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[4], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ==================
// API Server Handler
// ==================

type aPIServer struct {
	API
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
	jsonCamelCase    bool   // JSON fields are serialized as lowerCamelCase rather than keeping the original proto names
}

// NewAPIServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewAPIServer(svc API, opts ...interface{}) TwirpServer {
	serverOpts := newServerOpts(opts)

	// Using ReadOpt allows backwards and forwards compatibility with new options in the future
	jsonSkipDefaults := false
	_ = serverOpts.ReadOpt("jsonSkipDefaults", &jsonSkipDefaults)
	jsonCamelCase := false
	_ = serverOpts.ReadOpt("jsonCamelCase", &jsonCamelCase)
	var pathPrefix string
	if ok := serverOpts.ReadOpt("pathPrefix", &pathPrefix); !ok {
		pathPrefix = "/twirp" // default prefix
	}

	return &aPIServer{
		API:              svc,
		hooks:            serverOpts.Hooks,
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		pathPrefix:       pathPrefix,
		jsonSkipDefaults: jsonSkipDefaults,
		jsonCamelCase:    jsonCamelCase,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *aPIServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *aPIServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// APIPathPrefix is a convenience constant that may identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// with the default "/twirp" prefix and default CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const APIPathPrefix = "/twirp/rpc.API/"

func (s *aPIServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "rpc")
	ctx = ctxsetters.WithServiceName(ctx, "API")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "rpc.API" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "GetActiveSchema":
		s.serveGetActiveSchema(ctx, resp, req)
		return
	case "RunSQLQuery":
		s.serveRunSQLQuery(ctx, resp, req)
		return
	case "GetTrace":
		s.serveGetTrace(ctx, resp, req)
		return
	case "ListTraces":
		s.serveListTraces(ctx, resp, req)
		return
	case "ListTools":
		s.serveListTools(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *aPIServer) serveGetActiveSchema(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetActiveSchemaJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetActiveSchemaProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *aPIServer) serveGetActiveSchemaJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetActiveSchema")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(GetSchemaRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.API.GetActiveSchema
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetSchemaRequest) (*GetSchemaResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetSchemaRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetSchemaRequest) when calling interceptor")
					}
					return s.API.GetActiveSchema(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetSchemaResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetSchemaResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetSchemaResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetSchemaResponse and nil error while calling GetActiveSchema. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *aPIServer) serveGetActiveSchemaProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetActiveSchema")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(GetSchemaRequest)
	if err = proto1.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.API.GetActiveSchema
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetSchemaRequest) (*GetSchemaResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetSchemaRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetSchemaRequest) when calling interceptor")
					}
					return s.API.GetActiveSchema(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetSchemaResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetSchemaResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetSchemaResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetSchemaResponse and nil error while calling GetActiveSchema. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto1.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *aPIServer) serveRunSQLQuery(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveRunSQLQueryJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveRunSQLQueryProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *aPIServer) serveRunSQLQueryJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "RunSQLQuery")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(SQLQueryInput)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.API.RunSQLQuery
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *SQLQueryInput) (*SQLQueryResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SQLQueryInput)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SQLQueryInput) when calling interceptor")
					}
					return s.API.RunSQLQuery(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SQLQueryResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SQLQueryResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *SQLQueryResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *SQLQueryResponse and nil error while calling RunSQLQuery. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *aPIServer) serveRunSQLQueryProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "RunSQLQuery")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(SQLQueryInput)
	if err = proto1.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.API.RunSQLQuery
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *SQLQueryInput) (*SQLQueryResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*SQLQueryInput)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*SQLQueryInput) when calling interceptor")
					}
					return s.API.RunSQLQuery(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*SQLQueryResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*SQLQueryResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *SQLQueryResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *SQLQueryResponse and nil error while calling RunSQLQuery. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto1.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *aPIServer) serveGetTrace(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveGetTraceJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveGetTraceProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *aPIServer) serveGetTraceJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetTrace")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(GetTraceRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.API.GetTrace
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetTraceRequest) (*GetTraceResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetTraceRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetTraceRequest) when calling interceptor")
					}
					return s.API.GetTrace(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetTraceResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetTraceResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetTraceResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetTraceResponse and nil error while calling GetTrace. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *aPIServer) serveGetTraceProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "GetTrace")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(GetTraceRequest)
	if err = proto1.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.API.GetTrace
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *GetTraceRequest) (*GetTraceResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*GetTraceRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*GetTraceRequest) when calling interceptor")
					}
					return s.API.GetTrace(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*GetTraceResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*GetTraceResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *GetTraceResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *GetTraceResponse and nil error while calling GetTrace. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto1.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *aPIServer) serveListTraces(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveListTracesJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveListTracesProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *aPIServer) serveListTracesJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListTraces")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(ListTracesRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.API.ListTraces
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListTracesRequest) (*ListTracesResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListTracesRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListTracesRequest) when calling interceptor")
					}
					return s.API.ListTraces(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListTracesResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListTracesResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ListTracesResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListTracesResponse and nil error while calling ListTraces. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *aPIServer) serveListTracesProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListTraces")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(ListTracesRequest)
	if err = proto1.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.API.ListTraces
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListTracesRequest) (*ListTracesResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListTracesRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListTracesRequest) when calling interceptor")
					}
					return s.API.ListTraces(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListTracesResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListTracesResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ListTracesResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListTracesResponse and nil error while calling ListTraces. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto1.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *aPIServer) serveListTools(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveListToolsJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveListToolsProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *aPIServer) serveListToolsJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListTools")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(ListToolsRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.API.ListTools
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListToolsRequest) (*ListToolsResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListToolsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListToolsRequest) when calling interceptor")
					}
					return s.API.ListTools(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListToolsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListToolsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ListToolsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListToolsResponse and nil error while calling ListTools. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *aPIServer) serveListToolsProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListTools")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := io.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(ListToolsRequest)
	if err = proto1.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.API.ListTools
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ListToolsRequest) (*ListToolsResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ListToolsRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ListToolsRequest) when calling interceptor")
					}
					return s.API.ListTools(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ListToolsResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ListToolsResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ListToolsResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListToolsResponse and nil error while calling ListTools. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto1.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *aPIServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 0
}

func (s *aPIServer) ProtocGenTwirpVersion() string {
	return "v8.1.3"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *aPIServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "rpc", "API")
}

// =====
// Utils
// =====

// HTTPClient is the interface used by generated clients to send HTTP requests.
// It is fulfilled by *(net/http).Client, which is sufficient for most users.
// Users can provide their own implementation for special retry policies.
//
// HTTPClient implementations should not follow redirects. Redirects are
// automatically disabled if *(net/http).Client is passed to client
// constructors. See the withoutRedirects function in this file for more
// details.
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// TwirpServer is the interface generated server structs will support: they're
// HTTP handlers with additional methods for accessing metadata about the
// service. Those accessors are a low-level API for building reflection tools.
// Most people can think of TwirpServers as just http.Handlers.
type TwirpServer interface {
	http.Handler

	// ServiceDescriptor returns gzipped bytes describing the .proto file that
	// this service was generated from. Once unzipped, the bytes can be
	// unmarshalled as a
	// google.golang.org/protobuf/types/descriptorpb.FileDescriptorProto.
	//
	// The returned integer is the index of this particular service within that
	// FileDescriptorProto's 'Service' slice of ServiceDescriptorProtos. This is a
	// low-level field, expected to be used for reflection.
	ServiceDescriptor() ([]byte, int)

	// ProtocGenTwirpVersion is the semantic version string of the version of
	// twirp used to generate this file.
	ProtocGenTwirpVersion() string

	// PathPrefix returns the HTTP URL path prefix for all methods handled by this
	// service. This can be used with an HTTP mux to route Twirp requests.
	// The path prefix is in the form: "/<prefix>/<package>.<Service>/"
	// that is, everything in a Twirp route except for the <Method> at the end.
	PathPrefix() string
}

func newServerOpts(opts []interface{}) *twirp.ServerOptions {
	serverOpts := &twirp.ServerOptions{}
	for _, opt := range opts {
		switch o := opt.(type) {
		case twirp.ServerOption:
			o(serverOpts)
		case *twirp.ServerHooks: // backwards compatibility, allow to specify hooks as an argument
			twirp.WithServerHooks(o)(serverOpts)
		case nil: // backwards compatibility, allow nil value for the argument
			continue
		default:
			panic(fmt.Sprintf("Invalid option type %T, please use a twirp.ServerOption", o))
		}
	}
	return serverOpts
}

// WriteError writes an HTTP response with a valid Twirp error format (code, msg, meta).
// Useful outside of the Twirp server (e.g. http middleware), but does not trigger hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func WriteError(resp http.ResponseWriter, err error) {
	writeError(context.Background(), resp, err, nil)
}

// writeError writes Twirp errors in the response and triggers hooks.
func writeError(ctx context.Context, resp http.ResponseWriter, err error, hooks *twirp.ServerHooks) {
	// Convert to a twirp.Error. Non-twirp errors are converted to internal errors.
	var twerr twirp.Error
	if !errors.As(err, &twerr) {
		twerr = twirp.InternalErrorWith(err)
	}

	statusCode := twirp.ServerHTTPStatusFromErrorCode(twerr.Code())
	ctx = ctxsetters.WithStatusCode(ctx, statusCode)
	ctx = callError(ctx, hooks, twerr)

	respBody := marshalErrorToJSON(twerr)

	resp.Header().Set("Content-Type", "application/json") // Error responses are always JSON
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBody)))
	resp.WriteHeader(statusCode) // set HTTP status code and send response

	_, writeErr := resp.Write(respBody)
	if writeErr != nil {
		// We have three options here. We could log the error, call the Error
		// hook, or just silently ignore the error.
		//
		// Logging is unacceptable because we don't have a user-controlled
		// logger; writing out to stderr without permission is too rude.
		//
		// Calling the Error hook would confuse users: it would mean the Error
		// hook got called twice for one request, which is likely to lead to
		// duplicated log messages and metrics, no matter how well we document
		// the behavior.
		//
		// Silently ignoring the error is our least-bad option. It's highly
		// likely that the connection is broken and the original 'err' says
		// so anyway.
		_ = writeErr
	}

	callResponseSent(ctx, hooks)
}

// sanitizeBaseURL parses the the baseURL, and adds the "http" scheme if needed.
// If the URL is unparsable, the baseURL is returned unchanged.
func sanitizeBaseURL(baseURL string) string {
	u, err := url.Parse(baseURL)
	if err != nil {
		return baseURL // invalid URL will fail later when making requests
	}
	if u.Scheme == "" {
		u.Scheme = "http"
	}
	return u.String()
}

// baseServicePath composes the path prefix for the service (without <Method>).
// e.g.: baseServicePath("/twirp", "my.pkg", "MyService")
//
//	returns => "/twirp/my.pkg.MyService/"
//
// e.g.: baseServicePath("", "", "MyService")
//
//	returns => "/MyService/"
func baseServicePath(prefix, pkg, service string) string {
	fullServiceName := service
	if pkg != "" {
		fullServiceName = pkg + "." + service
	}
	return path.Join("/", prefix, fullServiceName) + "/"
}

// parseTwirpPath extracts path components form a valid Twirp route.
// Expected format: "[<prefix>]/<package>.<Service>/<Method>"
// e.g.: prefix, pkgService, method := parseTwirpPath("/twirp/pkg.Svc/MakeHat")
func parseTwirpPath(path string) (string, string, string) {
	parts := strings.Split(path, "/")
	if len(parts) < 2 {
		return "", "", ""
	}
	method := parts[len(parts)-1]
	pkgService := parts[len(parts)-2]
	prefix := strings.Join(parts[0:len(parts)-2], "/")
	return prefix, pkgService, method
}

// getCustomHTTPReqHeaders retrieves a copy of any headers that are set in
// a context through the twirp.WithHTTPRequestHeaders function.
// If there are no headers set, or if they have the wrong type, nil is returned.
func getCustomHTTPReqHeaders(ctx context.Context) http.Header {
	header, ok := twirp.HTTPRequestHeaders(ctx)
	if !ok || header == nil {
		return nil
	}
	copied := make(http.Header)
	for k, vv := range header {
		if vv == nil {
			copied[k] = nil
			continue
		}
		copied[k] = make([]string, len(vv))
		copy(copied[k], vv)
	}
	return copied
}

// newRequest makes an http.Request from a client, adding common headers.
func newRequest(ctx context.Context, url string, reqBody io.Reader, contentType string) (*http.Request, error) {
	req, err := http.NewRequest("POST", url, reqBody)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if customHeader := getCustomHTTPReqHeaders(ctx); customHeader != nil {
		req.Header = customHeader
	}
	req.Header.Set("Accept", contentType)
	req.Header.Set("Content-Type", contentType)
	req.Header.Set("Twirp-Version", "v8.1.3")
	return req, nil
}

// JSON serialization for errors
type twerrJSON struct {
	Code string            `json:"code"`
	Msg  string            `json:"msg"`
	Meta map[string]string `json:"meta,omitempty"`
}

// marshalErrorToJSON returns JSON from a twirp.Error, that can be used as HTTP error response body.
// If serialization fails, it will use a descriptive Internal error instead.
func marshalErrorToJSON(twerr twirp.Error) []byte {
	// make sure that msg is not too large
	msg := twerr.Msg()
	if len(msg) > 1e6 {
		msg = msg[:1e6]
	}

	tj := twerrJSON{
		Code: string(twerr.Code()),
		Msg:  msg,
		Meta: twerr.MetaMap(),
	}

	buf, err := json.Marshal(&tj)
	if err != nil {
		buf = []byte("{\"type\": \"" + twirp.Internal + "\", \"msg\": \"There was an error but it could not be serialized into JSON\"}") // fallback
	}

	return buf
}

// errorFromResponse builds a twirp.Error from a non-200 HTTP response.
// If the response has a valid serialized Twirp error, then it's returned.
// If not, the response status code is used to generate a similar twirp
// error. See twirpErrorFromIntermediary for more info on intermediary errors.
func errorFromResponse(resp *http.Response) twirp.Error {
	statusCode := resp.StatusCode
	statusText := http.StatusText(statusCode)

	if isHTTPRedirect(statusCode) {
		// Unexpected redirect: it must be an error from an intermediary.
		// Twirp clients don't follow redirects automatically, Twirp only handles
		// POST requests, redirects should only happen on GET and HEAD requests.
		location := resp.Header.Get("Location")
		msg := fmt.Sprintf("unexpected HTTP status code %d %q received, Location=%q", statusCode, statusText, location)
		return twirpErrorFromIntermediary(statusCode, msg, location)
	}

	respBodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return wrapInternal(err, "failed to read server error response body")
	}

	var tj twerrJSON
	dec := json.NewDecoder(bytes.NewReader(respBodyBytes))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&tj); err != nil || tj.Code == "" {
		// Invalid JSON response; it must be an error from an intermediary.
		msg := fmt.Sprintf("Error from intermediary with HTTP status code %d %q", statusCode, statusText)
		return twirpErrorFromIntermediary(statusCode, msg, string(respBodyBytes))
	}

	errorCode := twirp.ErrorCode(tj.Code)
	if !twirp.IsValidErrorCode(errorCode) {
		msg := "invalid type returned from server error response: " + tj.Code
		return twirp.InternalError(msg).WithMeta("body", string(respBodyBytes))
	}

	twerr := twirp.NewError(errorCode, tj.Msg)
	for k, v := range tj.Meta {
		twerr = twerr.WithMeta(k, v)
	}
	return twerr
}

// twirpErrorFromIntermediary maps HTTP errors from non-twirp sources to twirp errors.
// The mapping is similar to gRPC: https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md.
// Returned twirp Errors have some additional metadata for inspection.
func twirpErrorFromIntermediary(status int, msg string, bodyOrLocation string) twirp.Error {
	var code twirp.ErrorCode
	if isHTTPRedirect(status) { // 3xx
		code = twirp.Internal
	} else {
		switch status {
		case 400: // Bad Request
			code = twirp.Internal
		case 401: // Unauthorized
			code = twirp.Unauthenticated
		case 403: // Forbidden
			code = twirp.PermissionDenied
		case 404: // Not Found
			code = twirp.BadRoute
		case 429: // Too Many Requests
			code = twirp.ResourceExhausted
		case 502, 503, 504: // Bad Gateway, Service Unavailable, Gateway Timeout
			code = twirp.Unavailable
		default: // All other codes
			code = twirp.Unknown
		}
	}

	twerr := twirp.NewError(code, msg)
	twerr = twerr.WithMeta("http_error_from_intermediary", "true") // to easily know if this error was from intermediary
	twerr = twerr.WithMeta("status_code", strconv.Itoa(status))
	if isHTTPRedirect(status) {
		twerr = twerr.WithMeta("location", bodyOrLocation)
	} else {
		twerr = twerr.WithMeta("body", bodyOrLocation)
	}
	return twerr
}

func isHTTPRedirect(status int) bool {
	return status >= 300 && status <= 399
}

// wrapInternal wraps an error with a prefix as an Internal error.
// The original error cause is accessible by github.com/pkg/errors.Cause.
func wrapInternal(err error, prefix string) twirp.Error {
	return twirp.InternalErrorWith(&wrappedError{prefix: prefix, cause: err})
}

type wrappedError struct {
	prefix string
	cause  error
}

func (e *wrappedError) Error() string { return e.prefix + ": " + e.cause.Error() }
func (e *wrappedError) Unwrap() error { return e.cause } // for go1.13 + errors.Is/As
func (e *wrappedError) Cause() error  { return e.cause } // for github.com/pkg/errors

// ensurePanicResponses makes sure that rpc methods causing a panic still result in a Twirp Internal
// error response (status 500), and error hooks are properly called with the panic wrapped as an error.
// The panic is re-raised so it can be handled normally with middleware.
func ensurePanicResponses(ctx context.Context, resp http.ResponseWriter, hooks *twirp.ServerHooks) {
	if r := recover(); r != nil {
		// Wrap the panic as an error so it can be passed to error hooks.
		// The original error is accessible from error hooks, but not visible in the response.
		err := errFromPanic(r)
		twerr := &internalWithCause{msg: "Internal service panic", cause: err}
		// Actually write the error
		writeError(ctx, resp, twerr, hooks)
		// If possible, flush the error to the wire.
		f, ok := resp.(http.Flusher)
		if ok {
			f.Flush()
		}

		panic(r)
	}
}

// errFromPanic returns the typed error if the recovered panic is an error, otherwise formats as error.
func errFromPanic(p interface{}) error {
	if err, ok := p.(error); ok {
		return err
	}
	return fmt.Errorf("panic: %v", p)
}

// internalWithCause is a Twirp Internal error wrapping an original error cause,
// but the original error message is not exposed on Msg(). The original error
// can be checked with go1.13+ errors.Is/As, and also by (github.com/pkg/errors).Unwrap
type internalWithCause struct {
	msg   string
	cause error
}

func (e *internalWithCause) Unwrap() error                               { return e.cause } // for go1.13 + errors.Is/As
func (e *internalWithCause) Cause() error                                { return e.cause } // for github.com/pkg/errors
func (e *internalWithCause) Error() string                               { return e.msg + ": " + e.cause.Error() }
func (e *internalWithCause) Code() twirp.ErrorCode                       { return twirp.Internal }
func (e *internalWithCause) Msg() string                                 { return e.msg }
func (e *internalWithCause) Meta(key string) string                      { return "" }
func (e *internalWithCause) MetaMap() map[string]string                  { return nil }
func (e *internalWithCause) WithMeta(key string, val string) twirp.Error { return e }

// malformedRequestError is used when the twirp server cannot unmarshal a request
func malformedRequestError(msg string) twirp.Error {
	return twirp.NewError(twirp.Malformed, msg)
}

// badRouteError is used when the twirp server cannot route a request
func badRouteError(msg string, method, url string) twirp.Error {
	err := twirp.NewError(twirp.BadRoute, msg)
	err = err.WithMeta("twirp_invalid_route", method+" "+url)
	return err
}

// withoutRedirects makes sure that the POST request can not be redirected.
// The standard library will, by default, redirect requests (including POSTs) if it gets a 302 or
// 303 response, and also 301s in go1.8. It redirects by making a second request, changing the
// method to GET and removing the body. This produces very confusing error messages, so instead we
// set a redirect policy that always errors. This stops Go from executing the redirect.
//
// We have to be a little careful in case the user-provided http.Client has its own CheckRedirect
// policy - if so, we'll run through that policy first.
//
// Because this requires modifying the http.Client, we make a new copy of the client and return it.
func withoutRedirects(in *http.Client) *http.Client {
	copy := *in
	copy.CheckRedirect = func(req *http.Request, via []*http.Request) error {
		if in.CheckRedirect != nil {
			// Run the input's redirect if it exists, in case it has side effects, but ignore any error it
			// returns, since we want to use ErrUseLastResponse.
			err := in.CheckRedirect(req, via)
			_ = err // Silly, but this makes sure generated code passes errcheck -blank, which some people use.
		}
		return http.ErrUseLastResponse
	}
	return &copy
}

// doProtobufRequest makes a Protobuf request to the remote Twirp service.
func doProtobufRequest(ctx context.Context, client HTTPClient, hooks *twirp.ClientHooks, url string, in, out proto1.Message) (_ context.Context, err error) {
	reqBodyBytes, err := proto1.Marshal(in)
	if err != nil {
		return ctx, wrapInternal(err, "failed to marshal proto request")
	}
	reqBody := bytes.NewBuffer(reqBodyBytes)
	if err = ctx.Err(); err != nil {
		return ctx, wrapInternal(err, "aborted because context was done")
	}

	req, err := newRequest(ctx, url, reqBody, "application/protobuf")
	if err != nil {
		return ctx, wrapInternal(err, "could not build request")
	}
	ctx, err = callClientRequestPrepared(ctx, hooks, req)
	if err != nil {
		return ctx, err
	}

	req = req.WithContext(ctx)
	resp, err := client.Do(req)
	if err != nil {
		return ctx, wrapInternal(err, "failed to do request")
	}
	defer func() { _ = resp.Body.Close() }()

	if err = ctx.Err(); err != nil {
		return ctx, wrapInternal(err, "aborted because context was done")
	}

	if resp.StatusCode != 200 {
		return ctx, errorFromResponse(resp)
	}

	respBodyBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return ctx, wrapInternal(err, "failed to read response body")
	}
	if err = ctx.Err(); err != nil {
		return ctx, wrapInternal(err, "aborted because context was done")
	}

	if err = proto1.Unmarshal(respBodyBytes, out); err != nil {
		return ctx, wrapInternal(err, "failed to unmarshal proto response")
	}
	return ctx, nil
}

// doJSONRequest makes a JSON request to the remote Twirp service.
func doJSONRequest(ctx context.Context, client HTTPClient, hooks *twirp.ClientHooks, url string, in, out proto1.Message) (_ context.Context, err error) {
	marshaler := &protojson.MarshalOptions{UseProtoNames: true}
	reqBytes, err := marshaler.Marshal(in)
	if err != nil {
		return ctx, wrapInternal(err, "failed to marshal json request")
	}
	if err = ctx.Err(); err != nil {
		return ctx, wrapInternal(err, "aborted because context was done")
	}

	req, err := newRequest(ctx, url, bytes.NewReader(reqBytes), "application/json")
	if err != nil {
		return ctx, wrapInternal(err, "could not build request")
	}
	ctx, err = callClientRequestPrepared(ctx, hooks, req)
	if err != nil {
		return ctx, err
	}

	req = req.WithContext(ctx)
	resp, err := client.Do(req)
	if err != nil {
		return ctx, wrapInternal(err, "failed to do request")
	}

	defer func() {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = wrapInternal(cerr, "failed to close response body")
		}
	}()

	if err = ctx.Err(); err != nil {
		return ctx, wrapInternal(err, "aborted because context was done")
	}

	if resp.StatusCode != 200 {
		return ctx, errorFromResponse(resp)
	}

	d := json.NewDecoder(resp.Body)
	rawRespBody := json.RawMessage{}
	if err := d.Decode(&rawRespBody); err != nil {
		return ctx, wrapInternal(err, "failed to unmarshal json response")
	}
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawRespBody, out); err != nil {
		return ctx, wrapInternal(err, "failed to unmarshal json response")
	}
	if err = ctx.Err(); err != nil {
		return ctx, wrapInternal(err, "aborted because context was done")
	}
	return ctx, nil
}

// Call twirp.ServerHooks.RequestReceived if the hook is available
func callRequestReceived(ctx context.Context, h *twirp.ServerHooks) (context.Context, error) {
	if h == nil || h.RequestReceived == nil {
		return ctx, nil
	}
	return h.RequestReceived(ctx)
}

// Call twirp.ServerHooks.RequestRouted if the hook is available
func callRequestRouted(ctx context.Context, h *twirp.ServerHooks) (context.Context, error) {
	if h == nil || h.RequestRouted == nil {
		return ctx, nil
	}
	return h.RequestRouted(ctx)
}

// Call twirp.ServerHooks.ResponsePrepared if the hook is available
func callResponsePrepared(ctx context.Context, h *twirp.ServerHooks) context.Context {
	if h == nil || h.ResponsePrepared == nil {
		return ctx
	}
	return h.ResponsePrepared(ctx)
}

// Call twirp.ServerHooks.ResponseSent if the hook is available
func callResponseSent(ctx context.Context, h *twirp.ServerHooks) {
	if h == nil || h.ResponseSent == nil {
		return
	}
	h.ResponseSent(ctx)
}

// Call twirp.ServerHooks.Error if the hook is available
func callError(ctx context.Context, h *twirp.ServerHooks, err twirp.Error) context.Context {
	if h == nil || h.Error == nil {
		return ctx
	}
	return h.Error(ctx, err)
}

func callClientResponseReceived(ctx context.Context, h *twirp.ClientHooks) {
	if h == nil || h.ResponseReceived == nil {
		return
	}
	h.ResponseReceived(ctx)
}

func callClientRequestPrepared(ctx context.Context, h *twirp.ClientHooks, req *http.Request) (context.Context, error) {
	if h == nil || h.RequestPrepared == nil {
		return ctx, nil
	}
	return h.RequestPrepared(ctx, req)
}

func callClientError(ctx context.Context, h *twirp.ClientHooks, err twirp.Error) {
	if h == nil || h.Error == nil {
		return
	}
	h.Error(ctx, err)
}

var twirpFileDescriptor0 = []byte{
	// 2009 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x58, 0x5f, 0x73, 0x1b, 0xb7,
	0x11, 0x17, 0xff, 0x1f, 0x97, 0x14, 0x45, 0xc1, 0xb2, 0x7c, 0xa1, 0xdb, 0xc6, 0x39, 0xc7, 0xb5,
	0xe2, 0x66, 0xa8, 0x46, 0xb5, 0x27, 0xb6, 0x1a, 0x67, 0x6c, 0x59, 0x8e, 0xa9, 0x8c, 0x9d, 0x28,
	0x27, 0x4d, 0x5e, 0x6f, 0x20, 0x1e, 0x48, 0xa1, 0x3a, 0x1e, 0x2e, 0x38, 0x50, 0x96, 0xd2, 0x97,
	0x76, 0xa6, 0x9d, 0xc9, 0x73, 0x1f, 0xfb, 0xde, 0x8f, 0xd0, 0x4f, 0xd0, 0x6f, 0xd4, 0xe7, 0x4e,
	0xa7, 0x83, 0x05, 0xee, 0x78, 0xa4, 0x68, 0xd5, 0x7d, 0xee, 0x13, 0xb9, 0x8b, 0xdf, 0x02, 0x8b,
	0xdd, 0x1f, 0x16, 0x8b, 0x83, 0xa6, 0x4c, 0x86, 0xfd, 0x44, 0x0a, 0x25, 0x48, 0x45, 0x26, 0xc3,
	0x5e, 0x3b, 0x1d, 0x9e, 0xb2, 0x09, 0x35, 0xaa, 0xde, 0x96, 0x48, 0x58, 0xac, 0x58, 0xc4, 0x26,
	0x4c, 0xc9, 0xcb, 0x6d, 0x54, 0x6e, 0x2b, 0x49, 0x87, 0x6c, 0xfb, 0xfc, 0x33, 0xf3, 0xc7, 0x22,
	0x3f, 0x1c, 0x0b, 0x31, 0x8e, 0x98, 0x81, 0x9c, 0x4c, 0x47, 0xdb, 0x8a, 0x4f, 0x58, 0xaa, 0xe8,
	0x24, 0x31, 0x00, 0xef, 0x09, 0x74, 0x5f, 0x31, 0x75, 0x84, 0xb3, 0xfb, 0xec, 0x87, 0x29, 0x4b,
	0x15, 0xb9, 0x07, 0x1d, 0x16, 0x9f, 0x73, 0x29, 0xe2, 0x09, 0x8b, 0x55, 0xc0, 0x43, 0xb7, 0x74,
	0xa7, 0xb4, 0xd5, 0xf4, 0x57, 0x0b, 0xda, 0x83, 0xd0, 0xdb, 0x85, 0xf5, 0x82, 0x69, 0x9a, 0x88,
	0x38, 0x65, 0xe4, 0x1e, 0xd4, 0x8d, 0xab, 0x68, 0xd3, 0xda, 0x59, 0x35, 0xeb, 0xf4, 0x2d, 0xcc,
	0x0e, 0x7a, 0x7f, 0x2d, 0xc1, 0xea, 0xd1, 0x77, 0xaf, 0xbf, 0x9b, 0x32, 0x79, 0x79, 0x10, 0x27,
	0x53, 0x45, 0x7e, 0x06, 0xcd, 0x44, 0x8a, 0xdf, 0xb1, 0xa1, 0x3a, 0xd8, 0xb7, 0xeb, 0xcd, 0x14,
	0xe4, 0x63, 0x98, 0x5b, 0x7c, 0xdf, 0x2d, 0x5f, 0xf5, 0x68, 0x9f, 0x6c, 0x40, 0xed, 0x07, 0x3d,
	0xa3, 0x5b, 0xc1, 0x51, 0x23, 0x90, 0x8f, 0xa0, 0xf9, 0x56, 0x72, 0xc5, 0xde, 0x88, 0x90, 0xb9,
	0xd5, 0x3b, 0xa5, 0x2d, 0x67, 0xb0, 0xe2, 0xcf, 0x54, 0x3f, 0x95, 0x4a, 0x7b, 0x6d, 0x80, 0x20,
	0x57, 0x78, 0xff, 0x28, 0x41, 0x37, 0x73, 0x2e, 0xdf, 0xd8, 0xaf, 0xa0, 0x9e, 0x2a, 0xaa, 0xa6,
	0x29, 0x3a, 0xd7, 0xd9, 0xb9, 0xd1, 0xd7, 0x29, 0xca, 0x60, 0x47, 0x38, 0xe4, 0x5b, 0x08, 0xf9,
	0x14, 0xd6, 0xd9, 0x05, 0x1b, 0x4e, 0x15, 0x17, 0xf1, 0xfe, 0x54, 0x52, 0xfd, 0x8b, 0x2e, 0xd7,
	0xfc, 0xab, 0x03, 0xe4, 0x0e, 0xb4, 0x24, 0x4b, 0xa7, 0x91, 0x4a, 0xbf, 0x3e, 0xfa, 0xf6, 0x1b,
	0xeb, 0x7c, 0x51, 0xa5, 0x83, 0xa3, 0x84, 0xa2, 0x91, 0x2f, 0xde, 0xa6, 0xb8, 0x85, 0x9a, 0x3f,
	0x53, 0xe8, 0x6d, 0x33, 0x29, 0x85, 0x74, 0x6b, 0x66, 0xdb, 0x28, 0x78, 0x9f, 0xc2, 0xda, 0x2b,
	0xa6, 0x8e, 0x35, 0x19, 0xb2, 0xc4, 0x7e, 0x00, 0x0e, 0x92, 0x63, 0x96, 0xd2, 0x06, 0xca, 0x07,
	0xa1, 0xe7, 0x23, 0x0f, 0x2c, 0xda, 0x6e, 0xf9, 0x4b, 0xa8, 0xe1, 0xb0, 0x4d, 0xe5, 0x56, 0x7f,
	0x8e, 0x76, 0x36, 0xb1, 0x86, 0x6d, 0xe7, 0x9f, 0xf5, 0xd1, 0x36, 0xdd, 0xa7, 0x8a, 0xfa, 0xc6,
	0xcc, 0xfb, 0x77, 0x09, 0xd6, 0x5f, 0xf3, 0xd4, 0xcc, 0x9a, 0xfe, 0x6f, 0xec, 0x22, 0x3b, 0x50,
	0x3f, 0x61, 0x23, 0x21, 0x19, 0xc6, 0xad, 0xb5, 0xd3, 0xeb, 0x1b, 0x2a, 0xf7, 0x33, 0x2a, 0xf7,
	0x8f, 0x33, 0x2a, 0xfb, 0x16, 0x49, 0x7e, 0x0d, 0x35, 0x3a, 0x52, 0x4c, 0x62, 0x08, 0xaf, 0x37,
	0x31, 0x40, 0xd2, 0x87, 0xc6, 0x88, 0x47, 0x8a, 0x49, 0x1d, 0xd6, 0xca, 0x56, 0x6b, 0x67, 0x03,
	0xd3, 0x9a, 0x7b, 0xfd, 0x15, 0x0e, 0xfa, 0x19, 0x48, 0x87, 0x3a, 0xe2, 0x13, 0xae, 0x30, 0xd4,
	0x35, 0xdf, 0x08, 0x64, 0x13, 0xea, 0x62, 0x34, 0x4a, 0x99, 0x72, 0xeb, 0xa8, 0xb6, 0x92, 0xf7,
	0x14, 0xd6, 0x16, 0x66, 0xd2, 0x13, 0x8c, 0x38, 0x8b, 0xb2, 0x4d, 0x1b, 0x41, 0x6b, 0xcf, 0x69,
	0x34, 0x65, 0x96, 0xd6, 0x46, 0xf0, 0xbe, 0x00, 0x52, 0x0c, 0x9f, 0xcd, 0xca, 0x2f, 0xa1, 0x8e,
	0xe1, 0xd5, 0x44, 0xd4, 0x1e, 0x77, 0xd0, 0x63, 0x04, 0x1d, 0x28, 0x36, 0xf1, 0xed, 0xa8, 0xf7,
	0x87, 0x0a, 0x34, 0x73, 0xed, 0x35, 0xa9, 0x5f, 0x92, 0x90, 0xf2, 0xb2, 0x84, 0x3c, 0x01, 0x48,
	0x15, 0x95, 0x2a, 0xd0, 0x25, 0xe4, 0x3d, 0x22, 0xdc, 0x44, 0xb4, 0x96, 0xc9, 0x23, 0x70, 0x58,
	0x1c, 0x1a, 0xc3, 0xea, 0x7f, 0x35, 0x6c, 0xb0, 0x38, 0x44, 0xb3, 0x39, 0x5e, 0x3b, 0x96, 0xd7,
	0xe4, 0x43, 0x68, 0x85, 0xf6, 0xe4, 0x04, 0x93, 0x14, 0x23, 0x5e, 0xf6, 0x21, 0x53, 0xbd, 0x49,
	0xc9, 0x6d, 0x68, 0x4a, 0x21, 0x54, 0x10, 0xd3, 0x09, 0x73, 0x1b, 0xb8, 0x15, 0x47, 0x2b, 0xbe,
	0xa1, 0x13, 0x46, 0x7e, 0x0e, 0x60, 0xab, 0x8a, 0xde, 0xa8, 0x33, 0x5f, 0x67, 0x42, 0x72, 0x17,
	0x56, 0x43, 0x96, 0x44, 0xe2, 0x32, 0x0b, 0x45, 0x13, 0x11, 0xed, 0x99, 0xf2, 0x20, 0x24, 0xf7,
	0x61, 0x4d, 0x4e, 0x63, 0xbd, 0x9b, 0xe0, 0x9c, 0xc9, 0x54, 0x9f, 0x6d, 0x40, 0x58, 0xc7, 0xaa,
	0xbf, 0x37, 0x5a, 0x8f, 0x40, 0x17, 0x13, 0x28, 0x44, 0x94, 0xd1, 0xdf, 0xfb, 0xc2, 0x9e, 0x09,
	0xa3, 0xb3, 0x39, 0xbd, 0x0f, 0x35, 0xa5, 0x15, 0x36, 0xa5, 0xeb, 0x98, 0xd2, 0xe7, 0x43, 0xbd,
	0xa1, 0x17, 0x22, 0x1e, 0xf1, 0xb1, 0x6f, 0xc6, 0xbd, 0x67, 0xd0, 0x7e, 0x41, 0x13, 0x7a, 0xc2,
	0x23, 0xae, 0x38, 0x4b, 0x49, 0x0f, 0x9c, 0xa1, 0x98, 0x68, 0xbf, 0x4c, 0x5d, 0x72, 0xfc, 0x5c,
	0xd6, 0xe1, 0xa3, 0xd3, 0x90, 0x2b, 0x4c, 0xa7, 0xe3, 0x1b, 0xc1, 0xfb, 0x57, 0x03, 0xda, 0xc5,
	0x99, 0x49, 0x07, 0xca, 0x39, 0x27, 0xca, 0x3c, 0x24, 0x04, 0xaa, 0x18, 0x39, 0x43, 0x02, 0xfc,
	0x4f, 0x6e, 0x41, 0x95, 0x0f, 0x45, 0x6c, 0x4a, 0xd3, 0x60, 0xc5, 0x47, 0xe9, 0xa7, 0x52, 0x49,
	0x27, 0x83, 0xe2, 0x64, 0x26, 0xda, 0x55, 0xb4, 0x01, 0xa3, 0xc2, 0x78, 0x7f, 0x00, 0x0e, 0x4d,
	0xb8, 0x19, 0x35, 0xe5, 0xa9, 0x41, 0x13, 0x8e, 0x43, 0x3b, 0xb9, 0xad, 0xba, 0x4c, 0x18, 0x26,
	0xb2, 0xb3, 0xb3, 0x6e, 0xcb, 0x8a, 0x71, 0xf1, 0xf8, 0x32, 0x61, 0xd9, 0x74, 0xfa, 0x3f, 0x79,
	0x01, 0x1d, 0x3e, 0x49, 0x74, 0x05, 0x8a, 0x95, 0xa9, 0xaa, 0x0d, 0x34, 0xbb, 0x3d, 0x67, 0x76,
	0x30, 0x07, 0xf1, 0x17, 0x4c, 0xc8, 0x36, 0xd4, 0xb9, 0xbe, 0x73, 0x52, 0xd7, 0xc1, 0x70, 0xdf,
	0xc2, 0x70, 0xdb, 0x04, 0x7d, 0xa5, 0x0f, 0xa4, 0x0d, 0xba, 0x85, 0x91, 0x87, 0xe0, 0x48, 0x9b,
	0x2a, 0xb7, 0x89, 0x26, 0xae, 0x35, 0x31, 0xca, 0xa2, 0x4d, 0x8e, 0x24, 0x7d, 0xa8, 0x29, 0xae,
	0x22, 0x86, 0xe4, 0x68, 0x65, 0x17, 0x86, 0x92, 0x3c, 0x1e, 0x1f, 0xb3, 0x49, 0x12, 0x51, 0xc5,
	0x06, 0x25, 0xdf, 0x60, 0x74, 0x2c, 0x1f, 0x41, 0xf3, 0x94, 0x45, 0x49, 0xa0, 0xd8, 0x85, 0x72,
	0x5b, 0xef, 0xb6, 0x29, 0xfb, 0x8e, 0xc6, 0x1d, 0xb3, 0x0b, 0xa5, 0xcd, 0xee, 0xea, 0xab, 0x51,
	0x71, 0x75, 0x19, 0xa4, 0x3c, 0x1e, 0x47, 0xcc, 0x6d, 0x1b, 0xca, 0x1a, 0xe5, 0x11, 0xea, 0x0a,
	0xa0, 0x24, 0x9a, 0x4a, 0x1a, 0xb9, 0xab, 0x45, 0xd0, 0x21, 0xea, 0xc8, 0x23, 0x68, 0x0f, 0x0b,
	0xe4, 0x72, 0x3b, 0xe8, 0x83, 0x21, 0x63, 0x91, 0x75, 0xfe, 0x1c, 0x8c, 0x3c, 0x86, 0x35, 0xc9,
	0xb4, 0x67, 0x61, 0x60, 0x32, 0x95, 0xba, 0x6b, 0x18, 0xa4, 0xb5, 0x02, 0x8d, 0x5f, 0xf3, 0xf8,
	0xcc, 0xef, 0x58, 0x9c, 0x51, 0xa5, 0xe4, 0x19, 0x40, 0x42, 0xc7, 0x3c, 0x36, 0x99, 0xec, 0xe2,
	0x72, 0xb7, 0xcd, 0x72, 0x53, 0x99, 0x0a, 0x79, 0x98, 0x0f, 0x9a, 0xe0, 0x0e, 0x2a, 0x7e, 0xc1,
	0x40, 0x6f, 0xfe, 0xbe, 0xae, 0xc7, 0xf1, 0x59, 0xea, 0xae, 0x17, 0x0e, 0xce, 0xcb, 0x0b, 0xc5,
	0x64, 0x4c, 0x23, 0x5c, 0xd3, 0x8c, 0x93, 0x97, 0xb0, 0xc9, 0x62, 0x25, 0x2f, 0xd1, 0xc5, 0x73,
	0x1d, 0x88, 0xcc, 0x57, 0xb2, 0xdc, 0xd7, 0x0d, 0x84, 0x3f, 0xb7, 0xe8, 0xcc, 0xe3, 0x5d, 0xe8,
	0xb2, 0xc9, 0x09, 0x0b, 0xc3, 0xc2, 0x66, 0x6f, 0x2c, 0x9f, 0x60, 0x2d, 0x03, 0x66, 0xb6, 0x5f,
	0x42, 0x77, 0xcc, 0x54, 0x30, 0x73, 0x43, 0xc4, 0xee, 0x06, 0xee, 0x79, 0xd1, 0x76, 0x50, 0xf5,
	0x3b, 0x63, 0xa6, 0x5e, 0x66, 0x1e, 0xe0, 0x5e, 0xf7, 0x1a, 0x50, 0x0b, 0xf4, 0xb9, 0xdb, 0x73,
	0xa0, 0x1e, 0x20, 0x6b, 0xb0, 0x6f, 0xc9, 0x39, 0xb3, 0xb7, 0x0a, 0xad, 0x60, 0x16, 0x9e, 0xbd,
	0x1b, 0xb0, 0x1e, 0x2c, 0x2e, 0xe8, 0xfd, 0xb3, 0x0a, 0xe4, 0x2a, 0xd3, 0xc9, 0x43, 0xe8, 0xe0,
	0x4d, 0x14, 0x44, 0x62, 0x68, 0xb2, 0x91, 0xb5, 0x6f, 0xda, 0xb3, 0xaf, 0x53, 0x11, 0x1f, 0x52,
	0x75, 0xea, 0xaf, 0x22, 0xe8, 0xb5, 0xc5, 0x90, 0x07, 0x00, 0xc6, 0x0a, 0x0f, 0x70, 0x19, 0x4f,
	0x62, 0xcb, 0x9e, 0x44, 0x3c, 0xba, 0x4d, 0x1c, 0xc6, 0x93, 0xfb, 0x11, 0xb4, 0x43, 0x9e, 0x26,
	0x11, 0xbd, 0x34, 0xc5, 0xc0, 0x76, 0x39, 0x56, 0x87, 0x05, 0x41, 0x17, 0x5f, 0x0b, 0x11, 0x32,
	0x64, 0xd2, 0x76, 0x3a, 0x99, 0xdd, 0xb7, 0x5a, 0x47, 0x5c, 0x68, 0x9c, 0xf3, 0x94, 0x9f, 0x44,
	0xcc, 0x5e, 0x0b, 0x99, 0x38, 0x7f, 0x7e, 0xea, 0xef, 0x3e, 0x3f, 0x2b, 0xf3, 0xe7, 0xe7, 0x09,
	0xac, 0x46, 0x42, 0x9c, 0x4d, 0x93, 0x2c, 0x27, 0x8d, 0xe5, 0x39, 0x29, 0xf9, 0x6d, 0x83, 0xcb,
	0x33, 0xb2, 0x34, 0xa3, 0xce, 0x72, 0xeb, 0xf2, 0x92, 0x8c, 0xea, 0xbe, 0x21, 0x12, 0xc3, 0x33,
	0x66, 0xae, 0x19, 0xc7, 0xb7, 0x12, 0xf9, 0xad, 0xbe, 0x85, 0x46, 0x74, 0x1a, 0xa9, 0xc0, 0xb4,
	0x05, 0x50, 0x38, 0x89, 0xfb, 0x66, 0xe4, 0x7b, 0x3d, 0x30, 0xa8, 0xe8, 0xab, 0x69, 0x26, 0xeb,
	0x49, 0x77, 0xa1, 0x95, 0xd0, 0x68, 0xc8, 0x4e, 0x45, 0xa4, 0x63, 0x78, 0x4d, 0x21, 0xa9, 0xfa,
	0x45, 0x64, 0xd6, 0x07, 0xcf, 0xf8, 0xd4, 0x85, 0x4e, 0x30, 0x17, 0x9a, 0xa5, 0x94, 0x42, 0xd8,
	0x9c, 0xbb, 0x7b, 0x1d, 0x68, 0x07, 0x85, 0x99, 0xbd, 0xbf, 0x54, 0xe0, 0xc6, 0x92, 0x5a, 0xf9,
	0xff, 0xcc, 0xba, 0x1e, 0x38, 0xa9, 0x90, 0x8a, 0xea, 0x19, 0x1b, 0xe6, 0xe2, 0xce, 0x64, 0xb2,
	0x05, 0x55, 0x5d, 0xb4, 0xde, 0x45, 0xa5, 0x92, 0x8f, 0xc3, 0xb6, 0xf6, 0xf3, 0x09, 0x1d, 0xb3,
	0x20, 0x91, 0xec, 0x9c, 0xb3, 0xb7, 0x96, 0x47, 0x6d, 0x54, 0x1e, 0x1a, 0xdd, 0x42, 0x52, 0x75,
	0x15, 0xd1, 0xe6, 0xde, 0xef, 0xa1, 0x5d, 0xa4, 0x12, 0x71, 0xf5, 0x03, 0x47, 0xbb, 0x6c, 0x7a,
	0x81, 0xc1, 0x8a, 0x6f, 0x65, 0xd2, 0x83, 0x06, 0x8f, 0x15, 0x1b, 0x33, 0x69, 0xde, 0x30, 0x83,
	0x15, 0x3f, 0x53, 0x90, 0x4d, 0xa8, 0x8d, 0x22, 0x41, 0x15, 0x46, 0xb6, 0x3c, 0x58, 0xf1, 0x8d,
	0x48, 0x36, 0xa0, 0x7a, 0x22, 0x44, 0x94, 0xbf, 0xb7, 0x50, 0xd2, 0x8b, 0x9b, 0xd6, 0x76, 0x00,
	0x9d, 0xf9, 0xf8, 0xe8, 0x80, 0x28, 0xfb, 0xdf, 0x36, 0x23, 0xb9, 0xac, 0xc7, 0x26, 0x54, 0x9e,
	0x85, 0xe2, 0x6d, 0x6c, 0x9b, 0x99, 0x5c, 0xf6, 0x7e, 0x01, 0x4e, 0x46, 0x14, 0xdd, 0xba, 0x24,
	0x54, 0x9d, 0x5a, 0x7b, 0xfc, 0xef, 0xfd, 0xa9, 0x04, 0xed, 0xe2, 0x85, 0x40, 0x3e, 0x81, 0x5a,
	0x44, 0x4f, 0x58, 0x64, 0xb9, 0xb6, 0x2c, 0x59, 0xbe, 0x41, 0x90, 0xfb, 0x50, 0x3d, 0x95, 0x6c,
	0x64, 0x5f, 0x20, 0x4b, 0x91, 0x08, 0x78, 0x67, 0x7f, 0x94, 0xd7, 0x6c, 0xef, 0xcf, 0x25, 0x80,
	0x59, 0x0e, 0xc9, 0x2d, 0x68, 0xe8, 0x86, 0x6e, 0xd6, 0x8d, 0xd7, 0xb5, 0x78, 0x10, 0x92, 0x8f,
	0xa1, 0x1a, 0x52, 0x45, 0xed, 0x92, 0x5d, 0x73, 0xe2, 0xa9, 0xa2, 0x6f, 0x68, 0x92, 0xf0, 0x78,
	0xec, 0xe3, 0xe8, 0xac, 0xb5, 0xa8, 0x5c, 0x47, 0xb8, 0xbc, 0xb5, 0x98, 0xdd, 0x18, 0xde, 0xdf,
	0xaa, 0xb0, 0xb9, 0xfc, 0x72, 0x25, 0x4f, 0xa1, 0x86, 0x2d, 0xbb, 0x0d, 0xcc, 0xfd, 0x6b, 0x2e,
	0xe2, 0x7e, 0xb1, 0xe3, 0x31, 0x56, 0xe4, 0x09, 0x54, 0x58, 0x1c, 0x5a, 0xc7, 0xdf, 0xdb, 0x58,
	0xdb, 0x90, 0x57, 0xd0, 0x4c, 0x34, 0x8b, 0x53, 0xfe, 0x63, 0xb6, 0xa5, 0x07, 0xd7, 0x4d, 0x70,
	0x48, 0xc7, 0xec, 0x88, 0xff, 0xc8, 0xb2, 0x96, 0x2b, 0xb1, 0x32, 0x79, 0x00, 0xcd, 0x98, 0x5d,
	0x28, 0x7d, 0x0b, 0x66, 0x2f, 0x8d, 0x85, 0x5a, 0xe2, 0xe8, 0x71, 0x6d, 0x4f, 0xfa, 0xd0, 0xc2,
	0x27, 0x74, 0x30, 0x14, 0xd3, 0xd8, 0x3c, 0xe8, 0xae, 0xa0, 0x01, 0x11, 0x2f, 0x34, 0xa0, 0x77,
	0x0a, 0xad, 0x62, 0xed, 0xba, 0x0b, 0xab, 0xd2, 0xdc, 0xa3, 0x01, 0x76, 0x89, 0x36, 0x8f, 0x6d,
	0xab, 0x34, 0x1f, 0x35, 0x1e, 0x42, 0x27, 0x6b, 0x07, 0x03, 0xf3, 0xec, 0x2b, 0x2f, 0x2d, 0x70,
	0xb2, 0x58, 0x1c, 0x7b, 0x7f, 0x2c, 0x41, 0x67, 0x7e, 0x8b, 0xef, 0xb7, 0xda, 0xbd, 0xa5, 0xab,
	0x35, 0x17, 0xa6, 0x37, 0x6f, 0x9c, 0xe2, 0xed, 0x52, 0xb1, 0x05, 0xaf, 0x50, 0x0d, 0xbc, 0x73,
	0x68, 0x15, 0x68, 0x47, 0xfa, 0x96, 0x96, 0xe6, 0x7d, 0xd2, 0x5b, 0xa4, 0x25, 0xfe, 0xc7, 0xcb,
	0xcd, 0x10, 0xb4, 0xf7, 0x39, 0x34, 0x73, 0x15, 0xe9, 0x42, 0xe5, 0x8c, 0x5d, 0x5a, 0x97, 0xf5,
	0xdf, 0xe5, 0xef, 0xdd, 0xdd, 0xf2, 0xe3, 0xd2, 0x83, 0x4f, 0xa0, 0x33, 0xff, 0x4d, 0x85, 0xb4,
	0xa0, 0x91, 0x4e, 0x87, 0x43, 0x96, 0xa6, 0xdd, 0x15, 0x02, 0x50, 0x1f, 0x51, 0x1e, 0xb1, 0xb0,
	0x5b, 0xda, 0xf9, 0x7b, 0x19, 0x2a, 0xcf, 0x0f, 0x0f, 0xc8, 0x33, 0xfc, 0xd0, 0x81, 0x9d, 0x1a,
	0x33, 0x9f, 0x99, 0xc8, 0x4d, 0x74, 0x70, 0xf1, 0xc3, 0x56, 0x6f, 0x73, 0x51, 0x6d, 0x3b, 0xf5,
	0xc7, 0xd0, 0xf2, 0xa7, 0x71, 0xb6, 0x2e, 0x21, 0x73, 0x9f, 0x76, 0x30, 0xb6, 0xbd, 0x9b, 0x73,
	0xba, 0xdc, 0xf2, 0x73, 0x70, 0xb2, 0xcf, 0x26, 0x64, 0x23, 0x9b, 0xbd, 0xf8, 0xcd, 0xa5, 0x77,
	0x73, 0x41, 0x6b, 0x0d, 0x9f, 0x02, 0xcc, 0xde, 0xf6, 0x64, 0x73, 0xfe, 0xab, 0x43, 0xf6, 0x58,
	0xec, 0xdd, 0xba, 0xa2, 0xb7, 0xe6, 0xbb, 0xd0, 0xcc, 0x5f, 0x91, 0x76, 0xb7, 0x8b, 0x2f, 0xcd,
	0xde, 0xe6, 0xa2, 0xda, 0xd8, 0x9e, 0xd4, 0xf1, 0xaa, 0xfc, 0xcd, 0x7f, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x1f, 0x79, 0x2e, 0xeb, 0x64, 0x14, 0x00, 0x00,
}
