#!/bin/bash

# This script is run after a user installs the @teamkeel/sdk package
# The purpose is to create a new "dummy" node_module directory in node_modules
# named .keel, which will contain all of the code generated by the keel-cli based on
# a schema file.

# To use local executable (e.g go build cmd/keel/main.go), do:
# npm install --postinstall_keel_generate --postinstall_keel_use_local_executable

src_dir="$npm_config_local_prefix"

executable_path=""

if $npm_config_postinstall_keel_use_local_executable; then
  echo 'ℹ️  Building keel executable from repo'
  cd ../../
  go build -o keel cmd/keel/main.go

  executable_path="$PWD/keel"
else
  if ! [ -x "$(command -v keel)" ]; then
    echo '⛔️  Error: keel is not installed.' >&2
    exit 1
  fi

  executable_path = "keel"
fi

eval $executable_path generate -d $src_dir > /dev/null

last_exit=$?

if [ $last_exit != 0 ]; then
  echo '⛔️  Generation failed'
else
  echo '✅ Generated code'
fi